// Generated by CoffeeScript 1.3.3
(function() {
  var Memory;

  Memory = (function() {

    function Memory() {
      this.data = {};
    }

    Memory.prototype.writeTree = function(path, data, cb) {
      return this.write(path, data, cb);
    };

    Memory.prototype.readTree = function(path, cb) {
      return this.read(path, cb);
    };

    Memory.prototype.writeData = function(path, data, cb) {
      return this.write(path, data, cb);
    };

    Memory.prototype.readData = function(path, cb) {
      return this.read(path, cb);
    };

    Memory.prototype.write = function(path, data, cb) {
      this.data[path] = data;
      return cb(null);
    };

    Memory.prototype.read = function(path, cb) {
      return cb(null, this.data[path]);
    };

    Memory.prototype.remove = function(path, cb) {
      delete this.data[path];
      return cb(null);
    };

    return Memory;

  })();

  module.exports = Memory;

}).call(this);
