// Generated by CoffeeScript 1.3.3
(function() {
  var Store, computeHash, _;

  _ = require('underscore');

  computeHash = require('./utils').hash;

  Store = (function() {

    function Store(backend, _arg) {
      this.backend = backend;
      this.serialize = _arg.serialize, this.deserialize = _arg.deserialize;
    }

    Store.prototype.write = function(obj) {
      var json;
      json = this.serialize(obj);
      return this.backend.write(json);
    };

    Store.prototype.read = function(hash) {
      var json;
      json = this.backend.read(hash);
      if (json) {
        return this.deserialize(json);
      } else {
        return void 0;
      }
    };

    Store.prototype.readAll = function(hashs) {
      var each, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = hashs.length; _i < _len; _i++) {
        each = hashs[_i];
        _results.push(this.read(each));
      }
      return _results;
    };

    Store.prototype.writeAll = function(trees) {
      var each, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = trees.length; _i < _len; _i++) {
        each = trees[_i];
        _results.push(this.write(each));
      }
      return _results;
    };

    return Store;

  })();

  module.exports = Store;

}).call(this);
