// Generated by CoffeeScript 1.3.3
(function() {
  var Store, computeHash, _;

  _ = require('underscore');

  computeHash = require('./utils').hash;

  Store = (function() {

    function Store(backend, _arg) {
      this.backend = backend;
      this.serialize = _arg.serialize, this.deserialize = _arg.deserialize;
    }

    Store.prototype.write = function(obj, cb) {
      var json;
      json = this.serialize(obj);
      return this.backend.write(json, cb);
    };

    Store.prototype.read = function(hash, cb) {
      var obj;
      obj = this;
      return this.backend.read(hash, function(err, json) {
        if (json) {
          return cb(null, obj.deserialize(json));
        } else {
          return cb(err, void 0);
        }
      });
    };

    return Store;

  })();

  module.exports = Store;

}).call(this);
