// Generated by CoffeeScript 1.3.3
(function() {
  var TrackingStore, computeHash, deserialize, serialize, _;

  _ = require('underscore');

  computeHash = require('./utils').hash;

  serialize = function(obj) {
    var sort, sorted;
    sort = function(arr) {
      return arr.sort(function(a, b) {
        return a[0] > b[0];
      });
    };
    obj.childTrees = sort(_.pairs(obj.childTrees));
    obj.childData = sort(_.pairs(obj.childData));
    obj.ancestors = obj.ancestors.sort();
    sorted = sort(_.pairs(obj));
    return JSON.stringify(sorted);
  };

  deserialize = function(string) {
    var parsed;
    parsed = _.object(JSON.parse(string));
    parsed.childTrees = _.object(parsed.childTrees);
    parsed.childData = _.object(parsed.childData);
    return parsed;
  };

  TrackingStore = (function() {

    function TrackingStore() {}

    TrackingStore.prototype._data = {};

    TrackingStore.prototype.write = function(tree) {
      var json, treeHash;
      json = serialize(tree);
      treeHash = computeHash(json);
      this._data[treeHash] = json;
      return treeHash;
    };

    TrackingStore.prototype.read = function(hash) {
      return deserialize(this._data[hash]);
    };

    return TrackingStore;

  })();

  module.exports = TrackingStore;

}).call(this);
