// Generated by CoffeeScript 1.3.3
(function() {
  var BackendWrapper, computeHash;

  computeHash = require('./utils').hash;

  BackendWrapper = (function() {

    function BackendWrapper(backend) {
      this.backend = backend;
    }

    BackendWrapper.prototype.write = function(data, cb) {
      var dataHash, json;
      json = JSON.stringify(data);
      dataHash = computeHash(json);
      return this.backend.writeData(dataHash, data, function(err) {
        return cb(null, dataHash);
      });
    };

    BackendWrapper.prototype.read = function(hash, cb) {
      return this.backend.readData(hash, cb);
    };

    return BackendWrapper;

  })();

  module.exports = BackendWrapper;

}).call(this);
